url: https://github.com/bogdan2web/atena
baseurl: 

# Site settings
title: Atena
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# path to images

# Team names, titles and social links
people:
- name: Atena
  pic: 1
  position: Artist
  social:
    - title: twitter
      url: #
 
- name: Bogdan Borlea
  pic: 2
  position: WebDesigner
  social:
    - title: twitter
      url: #
  
# Postal address (add as many lines as necessary)
address:
  - line: Decebal Street
  - line: Deva, Romania

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed


